# Generated by Django 2.2.12 on 2021-03-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('type_block', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_of_floors', models.IntegerField()),
                ('rooms_per_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('warden_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('Students', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=50)),
                ('roll_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_1_student', to='hostel_management.Students')),
                ('roll_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_2_student', to='hostel_management.Students')),
                ('roll_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_3_student', to='hostel_management.Students')),
            ],
        ),
        migrations.CreateModel(
            name='BlockWarden',
            fields=[
                ('warden_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hostel_management.Warden')),
                ('block_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.Building')),
            ],
        ),
    ]
