# Generated by Django 2.2.12 on 2021-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='warden_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
