# Generated by Django 2.2.12 on 2021-03-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_auto_20210312_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocks',
            new_name='Block',
        ),
    ]
