# Generated by Django 2.2.12 on 2021-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_auto_20210312_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
