# Generated by Django 2.2.12 on 2021-03-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_auto_20210310_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='block_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_name_building', to='hostel_management.Building'),
        ),
    ]
