# Generated by Django 2.2.12 on 2021-03-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0004_auto_20210310_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocks',
            unique_together={('block_name', 'room_no')},
        ),
    ]
